spring.datasource.url=jdbc:sqlserver://KTDEV:1433;databaseName=InternalTools;encrypt=true;trustServerCertificate=true
spring.datasource.username=kyc_app
spring.datasource.password=VeryStrong!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=dbo

spring.thymeleaf.cache=false

# ——— Mail account (Office 365) ———
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=kycdatabase@treppides.com
spring.mail.password=T.805655890303aq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# From must be allowed for the mailbox (usually must match username)
app.mail.from=kycdatabase@treppides.com

# application.properties
app.approvals.secret=change-me-to-a-long-random-string
app.ui.baseurl=https://tools.treppides.com:8080/